name: iOS IPA Build (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        
    - name: Get Flutter dependencies (first time)
      run: flutter pub get
      
    - name: Check iOS directory structure
      run: |
        ls -la ios/
        echo "--- Checking for Generated.xcconfig ---"
        ls -la ios/Flutter/ || echo "Flutter directory doesn't exist yet"
        
    - name: Clean and regenerate Flutter files
      run: |
        flutter clean
        flutter pub get
        flutter precache --ios
        
    - name: Setup CocoaPods
      run: |
        echo "--- Verifying Generated.xcconfig exists ---"
        ls -la ios/Flutter/Generated.xcconfig
        echo "--- Starting CocoaPods installation ---"
        cd ios
        pod --version
        pod install --repo-update --verbose
        
    - name: Build iOS App (без подписи для AltStore)
      run: |
        echo "--- Полная очистка среды ---"
        cd ios && pod deintegrate && cd ..
        flutter clean
        rm -rf ios/Pods
        rm -rf ios/Podfile.lock
        rm -rf ios/.symlinks
        rm -rf .dart_tool
        
        echo "--- Повторная инициализация ---"
        flutter pub get
        cd ios && pod install --repo-update && cd ..
        
        echo "--- Сборка без -G флага (исправленная стратегия) ---"
        # Сначала пробуем device сборку с отключенными отладочными символами
        flutter build ios --release --no-codesign --no-tree-shake-icons || {
          echo "--- Device сборка не удалась, пробуем debug режим ---"
          flutter build ios --debug --no-codesign --simulator
        }
        
        echo "--- Поиск собранного приложения ---"
        find build/ios -name "*.app" -type d | head -5
        
        # Определяем путь к приложению (проверяем все возможные места)
        if [ -d "build/ios/iphoneos/Runner.app" ]; then
          APP_PATH="build/ios/iphoneos/Runner.app"
          echo "--- Найдено device приложение: $APP_PATH ---"
        elif [ -d "build/ios/iphonesimulator/Runner.app" ]; then
          APP_PATH="build/ios/iphonesimulator/Runner.app"
          echo "--- Найдено simulator приложение: $APP_PATH ---"
        elif [ -d "build/ios/Debug-iphonesimulator/Runner.app" ]; then
          APP_PATH="build/ios/Debug-iphonesimulator/Runner.app"
          echo "--- Найдено debug simulator приложение: $APP_PATH ---"
        else
          echo "--- Приложение не найдено, полный список: ---"
          find build -name "*.app" -type d 2>/dev/null || true
          ls -la build/ios/ 2>/dev/null || true
          echo "--- Пробуем создать базовое приложение ---"
          flutter build ios --debug --no-codesign
          APP_PATH="build/ios/Debug-iphoneos/Runner.app"
        fi
        
        # Проверяем что приложение действительно существует
        if [ ! -d "$APP_PATH" ]; then
          echo "--- Критическая ошибка: приложение не найдено ---"
          ls -la build/ios/
          exit 1
        fi
        
        echo "--- Создание .ipa ---"
        mkdir -p build/ios/ipa
        cp -r "$APP_PATH" build/ios/ipa/
        cd build/ios/ipa
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r TasteSmoke.ipa Payload/
        ls -la *.ipa
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-iOS-${{ github.run_number }}
        path: |
          build/ios/ipa/*.ipa
          build/ios/ipa/*.app
        retention-days: 30
        
    - name: Upload dSYM symbols (отладка)
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-dSYM-${{ github.run_number }}
        path: |
          build/ios/iphoneos/Runner.app.dSYM
          build/ios/Release-iphoneos/Runner.app.dSYM
        retention-days: 7
        if-no-files-found: ignore