name: iOS IPA Build (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        
    - name: Get Flutter dependencies (first time)
      run: flutter pub get
      
    - name: Check iOS directory structure
      run: |
        ls -la ios/
        echo "--- Checking for Generated.xcconfig ---"
        ls -la ios/Flutter/ || echo "Flutter directory doesn't exist yet"
        
    - name: Clean and regenerate Flutter files
      run: |
        flutter clean
        flutter pub get
        flutter precache --ios
        
    - name: Setup CocoaPods
      run: |
        echo "--- Verifying Generated.xcconfig exists ---"
        ls -la ios/Flutter/Generated.xcconfig
        echo "--- Starting CocoaPods installation ---"
        cd ios
        pod --version
        pod install --repo-update --verbose
        
    - name: Build iOS App (без подписи для AltStore)
      run: |
        echo "--- Полная очистка среды ---"
        cd ios && pod deintegrate && cd ..
        flutter clean
        rm -rf ios/Pods
        rm -rf ios/Podfile.lock
        rm -rf ios/.symlinks
        rm -rf .dart_tool
        
        echo "--- Повторная инициализация ---"
        flutter pub get
        cd ios && pod install --repo-update && cd ..
        
        echo "--- Сборка без -G флага (многоуровневая стратегия) ---"
        
        # Попытка 1: Device release build
        if flutter build ios --release --no-codesign --no-tree-shake-icons; then
          echo "--- Успешная device release сборка ---"
          APP_PATH="build/ios/iphoneos/Runner.app"
        # Попытка 2: Debug device build (меньше оптимизаций)
        elif flutter build ios --debug --no-codesign; then
          echo "--- Успешная device debug сборка ---"
          APP_PATH="build/ios/Debug-iphoneos/Runner.app"
        # Попытка 3: Полная очистка и debug simulator
        else
          echo "--- Device сборки не удались, полная очистка ---"
          flutter clean
          cd ios && pod deintegrate && pod install && cd ..
          flutter pub get
          
          if flutter build ios --debug --no-codesign --simulator; then
            echo "--- Успешная debug simulator сборка ---"
            APP_PATH="build/ios/Debug-iphonesimulator/Runner.app"
          else
            echo "--- Критическая ошибка: все стратегии сборки не удались ---"
            echo "Firebase модули:"
            find . -name "*firebase*" -o -name "*Firebase*" | head -10
            echo "Pod состояние:"
            cd ios && pod --version && pod list | grep -i firebase || true
            exit 1
          fi
        fi
        
        echo "--- Проверка собранного приложения ---"
        if [ ! -d "$APP_PATH" ]; then
          echo "--- Приложение не найдено по пути: $APP_PATH ---"
          find build -name "*.app" -type d 2>/dev/null || true
          exit 1
        fi
        
        echo "--- Найдено приложение: $APP_PATH ---"
        ls -la "$APP_PATH" | head -5
        
        echo "--- Создание .ipa ---"
        mkdir -p build/ios/ipa
        cp -r "$APP_PATH" build/ios/ipa/
        cd build/ios/ipa
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r TasteSmoke.ipa Payload/
        ls -la *.ipa
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-iOS-${{ github.run_number }}
        path: |
          build/ios/ipa/*.ipa
          build/ios/ipa/*.app
        retention-days: 30
        
    - name: Upload dSYM symbols (отладка)
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-dSYM-${{ github.run_number }}
        path: |
          build/ios/iphoneos/Runner.app.dSYM
          build/ios/Release-iphoneos/Runner.app.dSYM
        retention-days: 7
        if-no-files-found: ignore