name: iOS IPA Build (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor -v
        
    - name: Get Flutter dependencies (first time)
      run: flutter pub get
      
    - name: Check iOS directory structure
      run: |
        ls -la ios/
        echo "--- Checking for Generated.xcconfig ---"
        ls -la ios/Flutter/ || echo "Flutter directory doesn't exist yet"
        
    - name: Clean and regenerate Flutter files
      run: |
        flutter clean
        flutter pub get
        flutter precache --ios
        
    - name: Setup CocoaPods
      run: |
        echo "--- Verifying Generated.xcconfig exists ---"
        ls -la ios/Flutter/Generated.xcconfig
        echo "--- Starting CocoaPods installation ---"
        cd ios
        pod --version
        pod install --repo-update --verbose
        
    - name: Build iOS IPA
      run: |
        flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
          
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-iOS-${{ github.run_number }}
        path: build/ios/ipa/*.ipa
        retention-days: 30
        
    - name: Upload dSYM symbols (отладка)
      uses: actions/upload-artifact@v4
      with:
        name: TasteSmoke-dSYM-${{ github.run_number }}
        path: build/ios/archive/Runner.xcarchive/dSYMs/
        retention-days: 7